name: CI/CD for Book Webapp

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./book-webapp
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run unit tests and build application
        run: mvn --batch-mode --update-snapshots verify

      - name: Deploy to Staging
        env:
          PRIVATE_KEY: ${{secrets.STG_AWS_PRIVATE_KEY}}
          HOSTNAME: ${{secrets.STG_HOSTNAME}}
          USER_NAME : ${{secrets.STG_AWS_USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key 
          scp -o StrictHostKeyChecking=no -i private_key target/*.jar ${USER_NAME}@${HOSTNAME}:~/app.jar
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 'pkill -f app.jar&'
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 'nohup java -jar ~/app.jar > ~/spring.log 2>&1 &'

      - name: Wait until application starts
        run: sleep 180s
        shell: bash

      - name: Run system tests on Staging
        run: |
          cd ../book-webapp-api-tests
          mvn --batch-mode --update-snapshots verify

      - name: Deploy to Production
        env:
          PRIVATE_KEY: ${{secrets.PROD_AWS_PRIVATE_KEY}}
          HOSTNAME: ${{secrets.PROD_HOSTNAME}}
          USER_NAME : ${{secrets.PROD_AWS_USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key 
          scp -o StrictHostKeyChecking=no -i private_key target/*.jar ${USER_NAME}@${HOSTNAME}:~/app.jar
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 'pkill -f app.jar&'
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} 'nohup java -jar ~/app.jar > ~/spring.log 2>&1 &'
 
